import type { Metadata } from "next";
import { Inter, Mansalva, Manrope } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout-ui/Header";
import Footer from "@/components/layout-ui/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const mansalva = Mansalva({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-mansalva",
});
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
  weight: "400",
});
const manrope = Manrope({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
  weight: "400",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mansalva.variable} ${manrope.variable} ${inter.variable} flex flex-col my-0 mx-auto max-w-[144rem] antialiased`}
      >
        <Header />
        <main className="mt-20 bg-primary-1"> {children}</main>
        <Footer />
      </body>
    </html>
  );
}
